CREATE TABLE SYS.ENMASCARARDATOS (
	OWNER				VARCHAR2(20)				NOT NULL,
	TABLE_NAME			VARCHAR2(100)				NOT NULL,
	COLUMN_NAME			VARCHAR2(100)				NOT NULL,
	TIPO				VARCHAR2(40)				NOT NULL,
	ACTIVO				CHAR(1)						NOT NULL,
	PRIORIDAD			NUMBER								,
	OBSERVACION			VARCHAR2(200)
	);

CREATE TABLE SYS.ENMASCARARMANTTABLAS(
	OWNER				VARCHAR2(20)				NOT NULL,
	TABLE_NAME			VARCHAR2(100)				NOT NULL,
	ACTIVO				CHAR(1)						NOT NULL
	);

CREATE TABLE SYS.ENMASCARARLOG(
	RESULTADO			VARCHAR2(20)				NOT NULL,
	TIPO				VARCHAR2(50)				NOT NULL,
	OWNER				VARCHAR2(50)				NOT NULL,
	TABLE_NAME			VARCHAR2(50)				NOT NULL,
	ERRCODE				VARCHAR2(30)						,
	ERRDESC				VARCHAR2(1000)						,
	QUERY				VARCHAR2(3000)						,
	FECHAINICIO			VARCHAR2(50)						,
	FECHAFIN			VARCHAR2(50)
	);